baseURL = "https://alvar.ru/"
languageCode = "ru-ru"
title = "Дмитрий Плетнев"
theme = "m10c"
paginate = 10

[params]
author = "Alvar"
description = "Помогаю запускать сайты с нуля"
#menu_item_separator = " • "
avatar = "ava.jpg"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Блог"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Тэги"
    url = "/tags/"
  [[menu.main]]
    identifier = "portfolio"
    name = "Портфолио"
    url = "/portfolio/"

[[params.social]]
  name = "github"
  url = "https://github.com/vaga"

[[params.social]]
  name = "instagram"
  url = "https://vk.com/vaga"

[[params.social]]
  name = "facebook"
  url = "https://vk.com/vaga"

[[params.social]]
  name = "youtube"
  url = "https://vk.com/vaga"

[[params.social]]
  name = "telegram"
  url = "https://t.me/vaga"

[params.style]
  darkestColor = "#1F252A"
  darkColor = "#343D46"
  bodyBg = "#0b0e0f"
  #primaryColor = "#C695C6"
  primaryColor = "#99C794"
  lightColor = "#ccc"
  lightestColor = "#fff"