baseURL = "https://alvar.ru"
languageCode = "ru-ru"
title = "Дмитрий Плетнев"
theme = "m10c"
paginate = 10

[params]
author = "Alvar"
description = "Делаю сайты с нуля от идеи до выгрузки"
#menu_item_separator = " • "
avatar = "avatar.jpg"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Блог"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Теги"
    url = "/tags/"
  [[menu.main]]
    identifier = "portfolio"
    name = "Портфолио"
    url = "/portfolio/"

[[params.social]]
  name = "github"
  url = "https://github.com/waxmatuct"
  title = "Гитхаб"
  color= "#fff"

[[params.social]]
  name = "instagram"
  url = "https://instagram.com/alvar.alvheim"
  title = "Инстаграм"
  color = "#e1306c"

[[params.social]]
  name = "facebook-f"
  url = "https://www.facebook.com/alvarfromalvheim"
  title = "Фейсбук"
  color = "#e1306c"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/alvar_ru"
  title = "Твиттер"
  color = "#1da1f2"


[[params.social]]
  name = "telegram-plane"
  url = "https://t.me/alvar_ru"
  title = "Телега"
  color = "#08c"

[params.style]
  darkestColor = "#1C1C28"  #1F252A
  darkColor = "#28293D"  #343D46
  bodyBg = "#12151D" #0b0e0f
  primaryColor = "#5dd99f"
  #primaryColor = "#99C794"
  lightColor = "#ccc"
  lightestColor = "#fff"